Add matches overview page
boklisten/bl-next pull request #342
Opened 2023-06-13 23:52 UTC by LarsSelbekk

- chore: bump bl-model
- refactor(api): improve type safety of api SWR fetchers
- build(tsconfig): make unused things not error
- refactor(theme): add typography variants
- a11y: add html lang attribute
- feat(matches): add matches overview page
- feat(matches): poll matches for changes every 5s
- fixup! feat(matches): add matches overview page

2023-06-14 00:27 UTC, LarsSelbekk commented
<img width="1172" alt="noMatches" src="https://github.com/boklisten/bl-next/assets/6224384/17c12d08-e56f-4841-932e-fb247190b6de">

![oneMatchNotDone](https://github.com/boklisten/bl-next/assets/6224384/f40695c9-2f5a-4fc7-a286-f79e04d1d48d)
![partialMatch](https://github.com/boklisten/bl-next/assets/6224384/fe5fd596-2d3e-4b80-920d-7fee3b5a8cfe)
![combo](https://github.com/boklisten/bl-next/assets/6224384/37407fed-0d40-4c7b-9c3f-9c8a1da9434b)
![big](https://github.com/boklisten/bl-next/assets/6224384/38070ada-1275-42c6-9aaa-f71ecb6197f6)
![moreCombo](https://github.com/boklisten/bl-next/assets/6224384/9abfef7b-16ba-45f9-981e-afacc33e128b)
![moreGroups](https://github.com/boklisten/bl-next/assets/6224384/8d3bd8dd-02fb-47f8-9e26-e31af913ad5d)
![allDone](https://github.com/boklisten/bl-next/assets/6224384/9e293d44-ca90-41fc-8395-ec70f1d8bceb)

2023-06-14 00:29 UTC, LarsSelbekk commented
You should probably read the commit messsages here

2023-06-14 12:59 UTC, AdrianAndersen requested changes
Looks good for now, even though we might iterate on the design later. I was kinda picky about some things, but they should be really quick to implement/fix.

2023-06-14 12:59 UTC, AdrianAndersen commented on .eslintrc.js
> +    "unicorn/no-null": "off",
why?

2023-06-14 12:59 UTC, AdrianAndersen commented on src/components/match/matchesList/MatchesList.tsx
> +  }
You should use skeletons here. Really quick to add
```javascript
<Skeleton />
```

2023-06-14 12:59 UTC, AdrianAndersen commented on src/components/match/matchesList/MatchesList.tsx
> +  }
```Javascript
<Alert severity="info">Du har ingen overleveringer :)</Alert>
```

2023-06-14 12:59 UTC, AdrianAndersen commented on src/components/match/matchesList/helper.tsx
> +}
Seems like there is a lot of duplication in this method, why not just:
```javascript
export function formatActionsString(handoffItems: number, pickupItems: number) {
  const hasHandoffItems = handoffItems > 0;
  const hasPickupItems = pickupItems > 0;
  const actions: string[] = [];

  if (hasHandoffItems) {
    const handoffItemText = handoffItems === 1 ? "én bok" : `${handoffItems} bøker`;
    actions.push(`Du skal levere ${handoffItemText}`);
    if (hasPickupItems) {
      actions.push("og");
    }
  }

  if (hasPickupItems) {
    const pickupItemText = pickupItems === 1 ? "én bok" : `${pickupItems} bøker`;
    actions.push(`motta ${pickupItemText}`);
  }

  return actions.join(" ");
}
```

Not properly tested this btw, so please check that it works as before

2023-06-14 12:59 UTC, AdrianAndersen commented on src/components/match/matchesList/helper.tsx
> +  matches: T[]
no docs?

2023-06-14 12:59 UTC, AdrianAndersen commented on src/components/match/matchesList/helper.tsx
> +}
Would prefer template literals here

2023-06-14 12:59 UTC, AdrianAndersen commented on src/pages/match/index.tsx
> +      <div style={{ padding: "1em" }}>
why not rem?

2023-06-14 12:59 UTC, AdrianAndersen commented on src/utils/types.ts
> +    });
these are used by both bl-api and bl-next, and should therefore be appended to bl-model

2023-06-14 13:09 UTC, LarsSelbekk commented on src/components/match/matchesList/MatchesList.tsx
> +// TODO: real-time updating when receiver is scanning books?
Wasn't that removed in the latest commit? Oops if not

2023-06-14 13:13 UTC, LarsSelbekk commented on src/pages/match/index.tsx
> +      <div style={{ padding: "1em" }}>
Oopsie

2023-06-14 13:19 UTC, LarsSelbekk commented on .eslintrc.js
> +    "unicorn/no-null": "off",
Firstly I strongly disagree with the premise of the rule that undefined can be used instead, and secondly it makes it really hard to interface with bl-model types which use null

2023-06-14 13:30 UTC, AdrianAndersen commented on .eslintrc.js
> +    "unicorn/no-null": "off",
Sure, I kinda get that 😛 Can disable it for now at least

2023-06-14 13:31 UTC, AdrianAndersen commented on src/components/match/matchesList/MatchesList.tsx
> +// TODO: real-time updating when receiver is scanning books?
ah yeah. I went commit by commit, so did not see that it was removed when I encountered this

2023-06-14 13:32 UTC, AdrianAndersen commented on src/components/match/matchesList/MatchesList.tsx
> +  }
<Alert/> is not a popup, just a styled Box:
<img width="800" alt="image" src="https://github.com/boklisten/bl-next/assets/26925695/317409b0-2c88-4809-9a6b-a4f0fb721559">

2023-06-14 13:34 UTC, AdrianAndersen commented on src/components/match/matchesList/helper.tsx
> +}
Yeah, I prefer the concatted version. So up to you, but at the very least you should use a proper variable name

2023-06-14 13:35 UTC, AdrianAndersen commented on src/components/match/matchesList/helper.tsx
> +}
It becomes clean if you extract the logic into variables, and then use template literals

2023-06-14 18:01 UTC, LarsSelbekk commented
<img width="1172" alt="noMatches" src="https://github.com/boklisten/bl-next/assets/6224384/1d7e5a78-4a24-49e7-a12d-a74918f14eb4">

![oneMatchNotDone](https://github.com/boklisten/bl-next/assets/6224384/9a1890bf-7780-465c-8d71-8f61630161a8)
![partialMatch](https://github.com/boklisten/bl-next/assets/6224384/9e954563-1d97-45df-bd96-2060fe22e200)
![combo](https://github.com/boklisten/bl-next/assets/6224384/c30cd01b-91ec-430c-9653-684d57aa69e2)
![big](https://github.com/boklisten/bl-next/assets/6224384/0a50dd04-40a6-4da1-93cb-b85d0207069f)
![moreCombo](https://github.com/boklisten/bl-next/assets/6224384/8e447477-8ea9-48c0-9d7a-392e88fdcb04)
![moreGroups](https://github.com/boklisten/bl-next/assets/6224384/3df633d3-8aa4-412e-8291-dee359b8bd56)
![allDone](https://github.com/boklisten/bl-next/assets/6224384/9ceeee30-03ef-4a06-9df5-d20aef37e5f5)

2023-06-14 18:05 UTC, LarsSelbekk commented on src/components/match/MatchOverview.tsx
>  } from "@mui/material";
Done

2023-06-14 20:09 UTC, LarsSelbekk commented on src/components/match/matchesList/MatchesList.tsx
> +  }
Done in cb6b63d

2023-06-14 20:09 UTC, LarsSelbekk commented on src/components/match/matchesList/MatchesList.tsx
> +  }
Done in cb6b63d

2023-06-14 20:10 UTC, LarsSelbekk commented on src/pages/match/index.tsx
> +      <div style={{ padding: "1em" }}>
Done in cb6b63d

2023-06-14 20:10 UTC, LarsSelbekk commented on src/components/match/matchesList/helper.tsx
> +}
Done in cb6b63d

2023-06-14 20:10 UTC, LarsSelbekk commented on src/components/match/matchesList/helper.tsx
> +  matches: T[]
Done in cb6b63d

2023-06-14 20:10 UTC, LarsSelbekk commented on src/components/match/matchesList/helper.tsx
> +}
Name changed in cb6b63d

2023-06-14 20:10 UTC, LarsSelbekk commented on src/components/match/matchesList/MatchesList.tsx
> +  }
Done in cb6b63d

2023-06-15 08:33 UTC, AdrianAndersen approved these changes

2023-06-15 10:23 UTC, merged

2023-06-15 10:25 UTC, LarsSelbekk commented
Wouldn't it be better to have a single arrival endpoint from bl-web which can handle the token catching?

2023-06-15 10:25 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Mine Overleveringer"-side](https://trello.com/c/C7twbaZN/624-mine-overleveringer-side)

2023-06-15 10:58 UTC, AdrianAndersen commented
> Wouldn't it be better to have a single arrival endpoint from bl-web which can handle the token catching?

Yeah, I thought about that too. I have some plans for slowly integrating bl-next into bl-web, and in that case we really should do that yeah. I think the solution in this PR is ok for now, but definitely something we will look into this fall! 🚀