fix scanner comments
boklisten/bl-next pull request #371
Opened 2023-08-29 11:48 UTC by AdrianAndersen

- refactor(ManualRegistrationModal): loading => waiting
- refactor: unify scanner feedback state
- style: add max width for scanner tutorial
- style: add padding top for tutorial
- style: change close tutorial button color
- fix: close tutorial modal when user clicks outside of it
- style: change close scanner button color
- chore: slightly change info text to cover more cases

2023-08-29 11:49 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rette opp kommentarer fra merget PR](https://trello.com/c/uAZgwiCA/762-rette-opp-kommentarer-fra-merget-pr)

2023-08-29 17:19 UTC, LarsSelbekk commented
Still looks pretty bad (actually worse) on small screens (here iPhone 12 Pro)
![image](https://github.com/boklisten/bl-next/assets/6224384/dfb04355-a510-4a27-9064-e911efc3e52d)

2023-08-29 17:33 UTC, LarsSelbekk requested changes

2023-08-29 17:33 UTC, LarsSelbekk commented on src/components/matches/Scanner/Scanner.tsx
> +        handleClose={() => setFeedback({ ...feedback, visible: false })}
```suggestion
        handleClose={() => setFeedback((previous) => ({ ...previous, visible: false }))}
```

Okay I'm sure it has no effect in this instance, but my eyes hurt whenever someone does a state update based on the current state at update-queue time, not at the actual update time 🙃

2023-08-29 17:33 UTC, LarsSelbekk commented on src/components/matches/Scanner/Scanner.tsx
> +          setFeedback({ ...feedback, visible: false });
```suggestion
          setFeedback((previous) => ({ ...previous, visible: false }));
```
Ditto

2023-08-29 17:33 UTC, LarsSelbekk commented on src/components/matches/Scanner/ScannerTutorial.tsx
> +            maxWidth: "95%",
Still looks pretty bad (maybe worse) on e.g. iPhone 12 Pro
![image](https://github.com/boklisten/bl-next/assets/6224384/4643e5a5-0187-42e0-b767-0d7078f5019a)

2023-08-29 17:33 UTC, LarsSelbekk commented on src/components/matches/Scanner/ScannerTutorial.tsx
> +            paddingTop: "1rem",
Some marginBottom would also be nice

2023-09-06 09:04 UTC, AdrianAndersen commented on src/components/matches/Scanner/Scanner.tsx
> +        handleClose={() => setFeedback({ ...feedback, visible: false })}
Fixed in: https://github.com/boklisten/bl-next/pull/371/commits/f0a8bcf843c36ff791cb14d05f7da05c8bdb8ea1

2023-09-06 09:04 UTC, AdrianAndersen commented on src/components/matches/Scanner/Scanner.tsx
> +          setFeedback({ ...feedback, visible: false });
https://github.com/boklisten/bl-next/pull/371/commits/f0a8bcf843c36ff791cb14d05f7da05c8bdb8ea1

2023-09-06 09:04 UTC, AdrianAndersen commented on src/components/matches/Scanner/ScannerTutorial.tsx
> +            maxWidth: "95%",
https://github.com/boklisten/bl-next/pull/371/commits/f0a8bcf843c36ff791cb14d05f7da05c8bdb8ea1

2023-09-06 09:04 UTC, AdrianAndersen commented on src/components/matches/Scanner/ScannerTutorial.tsx
> +            paddingTop: "1rem",
https://github.com/boklisten/bl-next/pull/371/commits/f0a8bcf843c36ff791cb14d05f7da05c8bdb8ea1

2023-09-06 15:23 UTC, LarsSelbekk approved these changes

2023-09-13 07:42 UTC, merged