feat(match): reword mismatched book message
boklisten/bl-next pull request #436
Opened 2024-06-17 13:00 UTC by LarsSelbekk

2024-06-17 13:01 UTC, LarsSelbekk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Oppdatere tekster for tilbakemelding når man leverer noen andre sin bok](https://trello.com/c/6YGhPnNq/1070-oppdatere-tekster-for-tilbakemelding-n%C3%A5r-man-leverer-noen-andre-sin-bok)

2024-06-17 13:59 UTC, AdrianAndersen approved these changes

2024-06-17 14:00 UTC, AdrianAndersen requested changes
We need to adjust the message. See Slack

2024-06-18 21:09 UTC, AdrianAndersen approved these changes

2024-06-18 21:09 UTC, merged