Migrate Routes To App Router
boklisten/bl-next pull request #440
Opened 2024-06-25 18:43 UTC by AdrianAndersen

2024-07-01 22:28 UTC, LarsSelbekk requested changes
Leaving an extremely first-glance review so you have something to do, haven't gotten past the first page of reimplementation so more review is coming

2024-07-01 22:28 UTC, LarsSelbekk commented on next.config.js
> -  },
Not sure if it's this deletion but something borks; the Vercel preview tries to access localhost for the API

2024-07-01 22:28 UTC, LarsSelbekk commented on .eslintrc.js
> -    "plugin:unicorn/all",
Idk, I think it's better to remove those we don't agree with than to remove all of them

2024-07-01 22:28 UTC, LarsSelbekk commented on package.json
> -    "prepare": "husky install"
Why remove the pre-commit hooks? I understand the `install` command is deprecated, but from my reading of the docs there should still be something in the `prepare`-step (run `husky init` to fill it in)

2024-07-01 22:28 UTC, LarsSelbekk commented on src/utils/bl-config.ts
> +    basePath: process.env["API_URL"] ?? "http://localhost:1337/",
This could also be the problem - I remember something about needing to prefix with `NEXT_PUBLIC_` or something

2024-07-01 22:28 UTC, LarsSelbekk commented on src/utils/useGlobalState.ts
> +  setSelectedBranchId: (branchId) => set({ selectedBranchId: branchId }),
```suggestion
  selectBranch: (branchId) => set({ selectedBranchId: branchId }),
```
I would prefer if we could use less generic language for the dispatchers

2024-07-01 22:28 UTC, LarsSelbekk commented on src/app/info/branch/[branchId]/page.tsx
> +  const branches = (await fetcher(branchesUrl)) as Branch[];
```suggestion
  const branches = await fetcher<Branch[]>(branchesUrl);
```

2024-07-01 22:28 UTC, LarsSelbekk commented on src/app/info/branch/[branchId]/page.tsx
> +export const metadata: Metadata = {
nit: it would be nice to show the name of the branch in the title, using `generateMetadata` instead of `const metadata`

2024-07-02 13:57 UTC, AdrianAndersen commented on .eslintrc.js
> -    "plugin:unicorn/all",
Fine, I'll take her back 🦄

2024-07-02 14:00 UTC, AdrianAndersen commented on package.json
> -    "prepare": "husky install"
Sure, updated now

2024-07-02 14:44 UTC, AdrianAndersen commented on next.config.js
> -  },
Fixed now

2024-07-02 15:13 UTC, AdrianAndersen commented on src/utils/useGlobalState.ts
> +  setSelectedBranchId: (branchId) => set({ selectedBranchId: branchId }),
Dun

2024-07-02 20:06 UTC, LarsSelbekk commented on src/components/BranchSelect.tsx
>      add("bl-current-branch-id", branchId);
I think it's a bit dangerous to detach this from zustand. Can we use the [persistence middleware](https://docs.pmnd.rs/zustand/integrations/persisting-store-data#partialize)?

2024-07-02 20:24 UTC, LarsSelbekk commented on src/pages/index.tsx
> -          <NewsBanner editableText={newsBannerText} />
Big sad :(

2024-07-02 20:45 UTC, LarsSelbekk requested changes

2024-07-02 20:45 UTC, LarsSelbekk commented on src/pages/index.tsx
> -const Home: NextPage<HomeProps> = ({ newsBannerText }) => {
Since you're removing the home page, you should not leave it blank but instead redirect to bl-web using [`redirect`](https://nextjs.org/docs/app/api-reference/functions/redirect) (with `replace`)

2024-07-02 20:46 UTC, AdrianAndersen commented on src/app/layout.tsx
> +import "@mui/lab";
yeah, I fixed it towards what the docs use

2024-07-02 20:50 UTC, AdrianAndersen commented on src/components/AuthLinker.tsx
> +    const access_token = searchParameters?.get("access_token");
Nice spot!

2024-07-02 21:42 UTC, AdrianAndersen commented on src/components/BranchSelect.tsx
>      add("bl-current-branch-id", branchId);
dundundun

2024-07-02 22:05 UTC, LarsSelbekk approved these changes
🤠🤡

2024-07-02 22:05 UTC, merged