feat(auth): enable auth flow (with some redirects to bl-login)
boklisten/bl-next pull request #441
Opened 2024-07-03 21:45 UTC by AdrianAndersen

2024-07-03 21:46 UTC, AdrianAndersen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrer bl-login til bl-next](https://trello.com/c/7I2TCzEZ/1123-migrer-bl-login-til-bl-next)

2024-07-05 11:50 UTC, LarsSelbekk requested changes

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
> +                        if (!response.data?.[0].postalCity) {
UserDetailEditor: this is my fault for not actually testing the postal-code-lookup endpoint, but we get a 500 error whenever you try to type in the postal code field because the Bring API says a Norwegian postal code can only be 4 digits. This causes the Bring API to 400 and the http request to throw, bypassing the validation errors check. We should probably fix that on the API level so we don't send 500 for intended behavior.

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
>                        onChange: async (event) => {
Please move callbacks outside the JSX so it's more readable. This file is chonky enough (>600 lines!) that we may even want to extract custom hooks or something to a helper file.

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
> +      if (verifyBlError(result)) {
I don't like this API interface, where it either returns an opaque response type or an opaque error type - here it's very difficult to see whether all errors are handled. It probably deserves its own PR or something though, so I'm inclined to let it slide for now.

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
> +};
I think it's better to only take a `Moment` instead of responding that "this user is totally over 18" when their birthday is `null`

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
>      guardianEmail: userDetails.guardian?.email as string,
What justifies these casts? They don't seem accurate to me

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
> +  birthday: Moment | null;
Why optional?

2024-07-05 11:50 UTC, LarsSelbekk commented on src/components/user/UserDetailEditor.tsx
>      phoneNumber: userDetails.phone,
Github doesn't allow me to comment on unchanged lines, but since we're enabling this page I'm considering this a review of the entire page. I don't think we should split the first and last name in the frontend if we're not doing it in the database, though if you want to change that you're welcome to. I think it's a bit dangerous to just say the last word is the last name (take `Martin Luther Kin Jr.`), [names suck](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)

2024-07-05 18:36 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
> +                        if (!response.data?.[0].postalCity) {
Fixed in https://github.com/boklisten/bl-api/pull/532

2024-07-05 18:54 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
> +                            "/postal-code",
Yup, fixed

2024-07-05 18:55 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
> +      if (verifyBlError(result)) {
This has slightly been improved by now using `assertBlApiError`, but we probably need to do error boundaries at some point.

2024-07-05 19:05 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
>      phoneNumber: userDetails.phone,
Sure, dunno why I split, thought it looked cute I guess 😝

2024-07-05 21:16 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
>                        onChange: async (event) => {
✅

2024-07-05 21:21 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
> +  birthday: Moment | null;
It is not optional, there is validation to yell at you if you do not set it. This is for the first time you register, when you have not yet entered a birthday.

2024-07-05 21:21 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
>      guardianEmail: userDetails.guardian?.email as string,
Yah, removed them

2024-07-05 21:26 UTC, AdrianAndersen commented on src/components/user/UserDetailEditor.tsx
> +};
✅

2024-07-06 20:57 UTC, LarsSelbekk requested changes

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +    }
This is a bit ugly, can we do something in `AuthLinker` to suspend everything else until it's finished?

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +        setUserDetails(userDetails[0]);
Prefer destructuring

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +          <CircularProgress sx={{ mt: 1 }} />
Skeleton instead?

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +      fetchDetails();
I don't particularly having to write custom loading stuff when `Suspense` exists. As far as I know we would have to fetch on the server, but that seems fine (and ultimately preferable when we get cookie auth). Seemed to work with an intermediary server component in a POC edit

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +    <Card sx={{ paddingBottom: "2rem" }}>
I guess we should choose one of `rem` and `mui`'s integers instead of having both

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +      router.push("/auth/login?redirect=settings");
As discussed I think this should be an error boundary higher up in the tree, but only in the future.

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>              <InputAdornment
What's wrong with the browsers' default "Show password"-button? I don't see the need to re-implement it, and there are surely security and accessibility implications. (If you insist on it, at least move the `InputAdornment` into the `TextField`-props so it doesn't overlap with the text.)

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
> +          setApiError("Feil brukernavn eller passord");
None of the errors appear for me, only the browser's built-in validation :/

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>      <Container component="main" maxWidth="xs">
`component="main"` is a good idea, we should do that in the future along with `section` and `nav` and stuff (if you don't feel the urge to do it now)

2024-07-06 20:57 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
> +            "Noe gikk galt! Prøv igjen eller ta kontakt dersom problemet vedvarer.",
Wouldn't we want to show this even if the error isn't `BlError` (until we get a proper `ErrorBoundary`)?

2024-07-07 08:10 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                    {...register("birthday", fieldValidators.birthday)}
Yeh, #notourproblem

2024-07-07 19:19 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +          </Box>
Sure, I updated it to be more NAV-like now 🤠

2024-07-07 19:20 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +          </Box>
Also changed to onBlur, it was supa angry yeh

2024-07-07 19:25 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                    data-testid="postal-code-field"
Changed to only look up when the length is 4 nauw

2024-07-07 20:19 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                    autoComplete="postal-code"
Good call! ✅ Tested with simulator now, and it feels much better

2024-07-07 20:20 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                    id="phoneNumber"
✅

2024-07-07 20:20 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                  >
✅

2024-07-07 20:20 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                  disabled={!isSignUp}
I added a helperText saying you should contact us if you want to change your email

2024-07-07 20:28 UTC, AdrianAndersen commented on src/app/settings/page.tsx
> +  title: "Innstillinger | Boklisten.no",
Smoooooth

2024-07-07 20:34 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
>              <InputAdornment
What kind of black magic browsers are you using? None of my browsers have this feature 😮 The way I do it here (when the adornment is moved inside the Textfield) is the way people on the internet are doing it afaik: https://stackoverflow.com/a/60391397/13168694

2024-07-07 21:10 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +    <Card sx={{ paddingBottom: "2rem" }}>
After reading a bit, I prefer the MUI spacing approach, since it is scalable in themes. Since we are only using MUI, i also think it is appropriate to do it the way they intended you to. Soooo: I make a CHONKY commit where I replaced all REM with MUI Spacing. Since our root font size is 16px (==1rem) and the default MUI spacing unit is 8px, 1rem=2mui. Thus, I search and replaced so that we are consistent 🧹

2024-07-07 21:42 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +        setUserDetails(userDetails[0]);
✅

2024-07-07 21:43 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
>      <Container component="main" maxWidth="xs">
There was only one place where we had a <section>, so I fixed it. No navs present either.

2024-07-08 07:10 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +      router.push("/auth/login?redirect=settings");
#future

2024-07-08 10:32 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +          {isSignUp ? "Registrer deg" : "Innstillinger"}
I updated to brukerinnstillinger, as we have today. I plan to rename all our routes to norwegian names, but I think that should be another PR, as this one is already quite humongous. 🗻

2024-07-08 10:34 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +            {isSignUp ? "Registrer deg" : "Lagre"}
It is standard that it is not disabled yeah. It is a big nono to disable buttons in UX theory these days. Better to give the user feedback when they click it.

2024-07-08 10:39 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +        <CompanyLogo />
Yah, I agree. I just put it there since bl-login had it. But now that I think about it, the logo is always visible 2 cm above in the Nav bar... Removed it now

2024-07-08 11:24 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
> +          setApiError("Feil brukernavn eller passord");
Yeah, the FetchTokens threw an error that we did not catch. Improved it now, but we really need ErrorBoundaries in a later PR.

2024-07-08 11:24 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
> +            "Noe gikk galt! Prøv igjen eller ta kontakt dersom problemet vedvarer.",
Fixed.

2024-07-08 11:29 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +        <Typography component="h1" variant="h5" sx={{ my: 1 }}>
Sure, removed the component overrides now. In theory the first header on a page should be a h1, but nowadays I guess it does not matter that much. I mostly care about its appearance

2024-07-08 11:48 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +    }
Sure, I made it a boundary so that nothing below is returned before AuthLinker has eaten. 🥫

2024-07-08 11:54 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +      fetchDetails();
Not sure what you suggest here. The fetching needs to be done on the client, since we need auth. Since it is done on client, we need to wrap it in a useEffect. Can you please elaborate on your suggestion?

2024-07-08 12:13 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +          <CircularProgress sx={{ mt: 1 }} />
Yeah, this is highly dependent on the comment below, so will hold a bit on implementing this for now

2024-07-08 23:07 UTC, LarsSelbekk commented on src/components/user/Settings.tsx
> +      fetchDetails();
Yeah, you made me realize that was a bad idea. It worked, but it moved an API call to the server, which has side effects re: authentication and stuff. I don't think this is a very pretty way to do, but to get this merged at some point I'll relent here and say we can extract some hook `useUserDetail` or something later, with more advanced refreshing. The way it's written right now, I think there are theoretical issues where we don't change the user detail ID if there is an invalid access token with another user ID than the refresh token, but I can't see how that would happen so not a problem.

2024-07-08 23:26 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>              <InputAdornment
Oh ... apparently it's an Edge only feature, that blows my mind as I've always taken it for granted! 🤯 That's really disappointing. We'll have to do it your way then. With the InputAdornment it at least looks proper.

2024-07-09 01:26 UTC, LarsSelbekk requested changes
I haven't tested everything thoroughly yet, but I've now looked over all the code for things that look sus, and I think the UIs are pretty good now, but again, not tested everything.

2024-07-09 01:26 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +      setPostalCity(null);
Can I suggest some error-ish value when you've written 4 digits but they're not a valid district? Maybe an X, a warning icon, or the text `Ugyldig` or something

2024-07-09 01:26 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +const UserDetailEditor = ({
I still think this file and component is wayyy too long. Can you try to extract some long event handlers, more helper components, maybe a custom hook? I think it would also help to add some blank lines in the JSX between input fields, if you don't make those separate components, to break it up a little.

2024-07-09 01:26 UTC, LarsSelbekk commented on src/components/user/PasswordReset.tsx
> +        searchParams.get("resetToken") ?? "",
Not sure exactly which component/project is to blame (suspect `router.replace(pathname)` in `AuthLinker`), but the transition from bl-web strips the `resetToken` for me when clicking the e-mail link, so this never works.

2024-07-09 01:26 UTC, LarsSelbekk commented on src/components/user/PasswordReset.tsx
> +          </Box>
The "Show password"-button should definitely be more reusable. If the only way to do that is to make a specific password field component, that's fine IMO

2024-07-09 10:04 UTC, AdrianAndersen commented on src/api/blFetcher.ts
> +      throw data;
Yeah, it is ugly. Oh well, we can't save the world in one PR... 🤠

2024-07-09 10:05 UTC, AdrianAndersen commented on src/api/token.ts
> +  removeAll();
🍪 🍪

2024-07-09 10:06 UTC, AdrianAndersen commented on src/api/token.ts
> +  const tokens = await BlFetcher.post<
✅

2024-07-09 10:22 UTC, AdrianAndersen commented on src/app/auth/permission/denied/page.tsx
> +            administrator for spørsmål.
Defff 🔫

2024-07-09 10:22 UTC, AdrianAndersen commented on src/app/auth/permission/denied/page.tsx
> +    "Vi klarte ikke å logge deg inn. Vennligst prøv på nytt eller ta kontakt hvis problemet vedvarer.",
Heh I forgot to change it after I did some copy pasting 🤠

2024-07-09 10:22 UTC, AdrianAndersen commented on src/components/AuthLinker.tsx
> +      String(href).includes(BL_CONFIG.blAdmin.basePath)) &&
Yeah, that is silly. Removed it now.

2024-07-09 10:22 UTC, AdrianAndersen commented on src/components/BranchSelect.tsx
> +  const { data } = useSWR(
🧹 🧹 ✅

2024-07-09 10:23 UTC, AdrianAndersen commented on src/components/OrderHistory.tsx
> +  const [data] = await BlFetcher.get<Payment[]>(
✅

2024-07-09 10:23 UTC, AdrianAndersen commented on src/components/editableText/EditableTextEditor.tsx
> +    [{ header: "1" }, { header: 2 }, { header: "3" }],
Whoops. Was a bit quick when I did search and replace for removing REM. 😶

2024-07-09 10:23 UTC, AdrianAndersen commented on src/components/info/DynamicSubNav.tsx
> +              padding: "1 1.2",
Since this is a Style tag I think it is fair to use REM, since it is not part of the SX regime. Changed it back to REM.

2024-07-09 10:23 UTC, AdrianAndersen commented on src/components/matches/MatchDetail.tsx
> +    <Card sx={{ padding: "2 0 4 0" }}>
Yeah, this works since it is SX, not style. Updated to your suggestion.

2024-07-09 10:26 UTC, AdrianAndersen commented on src/components/matches/Matches.tsx
> +  }, []);
How could I forget our beautiful child? 🐙

2024-07-15 19:30 UTC, LarsSelbekk requested changes
Still not done. I've mostly tested the signup-form so far.

2024-07-15 19:30 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +              Eller, registrer deg med med epost
```suggestion
              Eller, registrer deg med epost
```
🤪🧌

2024-07-15 19:30 UTC, LarsSelbekk commented on src/components/user/SocialLoginButton.tsx
>        background: brandColor,
When hovering (or clicking on touch) the Google button, it turns blue (`:hover`-background-color takes precedence and is not overriden)

2024-07-15 19:30 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                          label="Fødselsdato"
This field is required, and since it uses a custom component I guess we'll have to add the asterisk manually.
```suggestion
                          label="Fødselsdato *"
```

2024-07-15 19:30 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                      label={<TermsAndConditionsDisclaimer />}
Not sure if there's a simpler way to make this required-true without the validator, but any way you accomplish it this should have an asterisk since it's mandatory.

2024-07-15 19:30 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>          <GoogleButton label={"Logg inn med Google"} />
These don't work for me locally, for signup or -in. Are they supposed to?
![image](https://github.com/user-attachments/assets/8c74ae8c-a14e-46d8-a778-7ececc95349d)
![image](https://github.com/user-attachments/assets/98fbb8fd-3b97-475d-818b-7d9042b77ed8)

2024-07-16 12:33 UTC, LarsSelbekk requested changes
Think this is the last of the comments at this stage. There are many, many minor things but also a few major.

2024-07-16 12:33 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>    const onSubmit: SubmitHandler<SignInFields> = async (data) => {
If the user is already logged in with a valid refresh token, login should be automatic. This is especially important because bladmin and bl-web can't read next's tokens, so may redirect to login even if the user is logged in in next.

2024-07-16 12:33 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +const UserDetailEditor = ({
Something here tries to pass a ref to a non-forwardref functional component.

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `UserDetailEditor`.
    at Controller (webpack-internal:///(app-pages-browser)/./node_modules/react-hook-form/dist/index.esm.mjs:567:37)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (webpack-internal:///(app-pages-browser)/./node_modules/@mui/material/Grid/Grid.js:387:89)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (webpack-internal:///(app-pages-browser)/./node_modules/@mui/material/Grid/Grid.js:387:89)
    at form
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Box (webpack-internal:///(app-pages-browser)/./node_modules/@mui/system/esm/createBox.js:36:76)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Grid (webpack-internal:///(app-pages-browser)/./node_modules/@mui/system/esm/Stack/createStack.js:160:24)
    at main
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Container (webpack-internal:///(app-pages-browser)/./node_modules/@mui/system/esm/Container/createContainer.js:119:19)
    at UserDetailEditor (webpack-internal:///(app-pages-browser)/./src/components/user/user-detail-editor/UserDetailEditor.tsx:76:11)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Paper (webpack-internal:///(app-pages-browser)/./node_modules/@mui/material/Paper/Paper.js:87:85)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@emotion/react/dist/emotion-element-43c6fea0.browser.esm.js:60:66)
    at Card (webpack-internal:///(app-pages-browser)/./node_modules/@mui/material/Card/Card.js:53:84)
    at UserSettings (webpack-internal:///(app-pages-browser)/./src/components/user/UserSettings.tsx:26:78)
```

2024-07-16 12:33 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
> +    router.push("/" + (searchParams.get("redirect") ?? ""));
I think these should be `replace` to stop "catching" you when you try to go backwards past a login barrier.

2024-07-16 12:33 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>              type="submit"
I think these and other submit-buttons should become disabled and get a spinner + loading text while submitting/processing

2024-07-16 12:33 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>      <Container component="main" maxWidth="xs">
There are some slight spacing differences with the register-page which cause some jumping when you click the links at the bottom to navigate between them, which doesn't look great.

2024-07-17 15:01 UTC, LarsSelbekk requested changes

2024-07-17 15:01 UTC, LarsSelbekk commented on src/components/matches/MatchDetail.tsx
> +    <Card sx={{ padding: [2, 0, 4, 0] }}>
It's probably not this line, but there are still some spacing/sizing problems on this page.
New:
![image](https://github.com/user-attachments/assets/a0d45582-8e44-4fce-b86e-28f75e4b72a4)
Old:
![image](https://github.com/user-attachments/assets/438291b3-391c-4544-b1d5-ff282522ba19)

2024-08-01 12:13 UTC, LarsSelbekk commented on src/components/user/PasswordReset.tsx
> +        searchParams.get("resetToken") ?? "",
Fixed in 824e622

2024-08-01 12:15 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/field-validators.ts
> +        : "Du må fylle inn et lovlig norsk telefonnummer (uten mellomrom og +47)",
Fixed in f8aa2b6

2024-08-01 14:24 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
> +                    title={showPassword ? "Skjul passord" : "Vis passord"}
Fixed in 3691976

2024-08-01 14:25 UTC, LarsSelbekk commented on src/components/user/PasswordReset.tsx
> +          </Box>
Fixed in 3691976

2024-08-01 17:01 UTC, LarsSelbekk commented on src/components/matches/Scanner/ScannerModal.tsx
> +          maxWidth: 100,
Fixed in 44b80d2

2024-08-01 17:12 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/field-validators.ts
> +    validate: (v) => (isEmail(v) ? true : "Du må fylle inn en gyldig epost"),
Fixed in ff0c795

2024-08-01 18:52 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +              Eller, registrer deg med med epost
Fixed in 0388f1d

2024-08-08 12:48 UTC, LarsSelbekk commented on src/components/matches/MatchDetail.tsx
> +    <Card sx={{ padding: [2, 0, 4, 0] }}>
Fixed in 44b80d2af80e7339c6dffb566e97a333c6d81de9

2024-08-08 12:53 UTC, AdrianAndersen commented on src/components/user/Settings.tsx
> +          <CircularProgress sx={{ mt: 1 }} />
I fixerino 🧑‍⚕️

2024-08-08 12:55 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
> +    router.push("/" + (searchParams.get("redirect") ?? ""));
Fixed in 75ba46a2b2408f98a628d964311ce5b13b16b003

2024-08-08 12:56 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>          <GoogleButton label={"Logg inn med Google"} />
Was missing some envs, testing

2024-08-08 13:39 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>          <GoogleButton label={"Logg inn med Google"} />
Works perfectly with the right envs (though one must ignore an error message in Facebook)

2024-08-08 13:53 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +  } = useForm<UserEditorFields>({ mode: "onBlur", defaultValues });
The switch is because of [`reValidateMode`](https://react-hook-form.com/docs/useform#reValidateMode), so intended and possible to change.

2024-08-08 14:25 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +  } = useForm<UserEditorFields>({ mode: "onBlur", defaultValues });
Fixed in f22b9a8

2024-08-08 14:26 UTC, LarsSelbekk commented on src/app/auth/forgot/page.tsx
>      try {
Used `onTouched `instead_

2024-08-08 14:29 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                        <InputAdornment position="start">+47</InputAdornment>
Ugly but won't fix

2024-08-08 14:40 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +      setPostalCity(null);
Won't-fix

2024-08-08 15:07 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +  const [showDetails, setShowDetails] = useState(!isSignUp);
I fixerino

2024-08-08 15:10 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +  const [showDetails, setShowDetails] = useState(!isSignUp);
Dun

2024-08-08 15:24 UTC, AdrianAndersen commented on src/components/user/SocialLoginButton.tsx
>        background: brandColor,
🏁

2024-08-08 15:25 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                          label="Fødselsdato"
✅

2024-08-08 15:38 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                      label={<TermsAndConditionsDisclaimer />}
Suresure ✅

2024-08-11 18:38 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
>            </Button>
I think it is good enough as is

2024-08-11 18:52 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/FieldErrorAlert.tsx
> +      sx={{ mt: 1 }}
Dun

2024-08-11 18:53 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                  <ListItem sx={{ display: "list-item" }} key={error.message}>
Dun

2024-08-11 18:53 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +            <Alert severity="error" sx={{ mt: 2 }}>
Homage added

2024-08-11 18:58 UTC, AdrianAndersen commented on src/app/auth/forgot/page.tsx
>        />
This is OK, since this is a client component. In the future, I want all components to be a wrapped server components at least to some degree, using the new Metadata API. For now tho, we can keep it this way.

2024-08-11 19:00 UTC, AdrianAndersen commented on src/app/auth/forgot/page.tsx
> +                {...register("email")}
back at it again

2024-08-11 19:02 UTC, AdrianAndersen commented on src/app/auth/logout/page.tsx
> +            seconds={3}
I fix

2024-08-11 19:10 UTC, AdrianAndersen commented on src/app/auth/logout/page.tsx
> +            seconds={3}
dun

2024-08-11 19:11 UTC, AdrianAndersen commented on src/components/BranchSelect.tsx
>    const { selectedBranchId, selectBranch } = useGlobalState();
I think it is quite readable now, so yeah, not priority to look into now

2024-08-11 19:13 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                  <ListItem sx={{ display: "list-item" }} key={error.message}>
Yeah, that is cool, but not pri for now 🤠

2024-08-11 19:15 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +            </DynamicLink>
As discussed, I think we gonna nah this for now. This is fine.

2024-08-11 19:17 UTC, AdrianAndersen commented on src/components/AuthLinker.tsx
> +export default function AuthLinker({ children }: { children: ReactNode }) {
This works

2024-08-11 19:28 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                              shouldValidate: true,
Semi-fixed in 6883820 - can't disable mui's red outline when you've partially filled out the date with the keyboard, but it's much better.

2024-08-11 20:26 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +const UserDetailEditor = ({
Fixed in 0fbdd1c

2024-08-11 20:27 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                              shouldValidate: true,
Fixed the last bit in 0fbdd1c

2024-08-11 21:39 UTC, LarsSelbekk commented on src/components/user/SignIn.tsx
>      <Container component="main" maxWidth="xs">
Fixed in c4c5d7b

2024-08-11 22:35 UTC, LarsSelbekk commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +            {isSignUp ? "Registrer deg" : "Lagre"}
Done in 25f8bab

2024-08-12 10:00 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +                  {emailConfirmationRequested ? (
Added an explict warning now: 
![image](https://github.com/user-attachments/assets/3cbf1406-2a24-448e-ab07-1759d8e1f367)

2024-08-12 11:39 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
>              type="submit"
✅

2024-08-12 11:41 UTC, AdrianAndersen commented on src/components/user/PasswordReset.tsx
> +export default function PasswordReset({ userId }: { userId: string }) {
Works for me, and on staging. Probably a you thing 🤠

2024-08-12 12:04 UTC, AdrianAndersen commented on src/components/user/SignIn.tsx
> +        <Typography variant="h5" sx={{ mt: 1 }}>
🏁

2024-08-12 12:09 UTC, AdrianAndersen commented on src/components/EmailConfirmer.tsx
> +    tryValidateEmail();
✅

2024-08-13 21:37 UTC, AdrianAndersen commented on src/components/user/user-detail-editor/UserDetailEditor.tsx
> +const UserDetailEditor = ({
u fixed 💯

2024-08-13 21:40 UTC, LarsSelbekk approved these changes

2024-08-13 21:40 UTC, merged